[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
package = "./plugins/netlify-plugin-store-posts-for-search"

[[plugins]]
package = "@netlify/plugin-sitemap"

